#!/usr/bin/env python3

import random
from time import sleep

from rgb7seg import NumberDisplay

numeral = NumberDisplay()

for i in range(9, -1, -1):
    if i > 6:
        numeral.display(i, numeral.colors['green'])
    elif i > 3:
        numeral.display(i, numeral.colors['yellow'])
    else:
        numeral.display(i, numeral.colors['red'])
    sleep(1)

sleep(4)

numeral.display()
