#!/usr/bin/env python3

import random
from time import sleep

from rgb7seg import NumberDisplay

numeral = NumberDisplay()

for c in 'abcdefghijklmnopqrstuvwxyz':
    while True:
        color = random.choice(list(numeral.colors.keys()))
        if color != 'black':
            break

    numeral.display(c, numeral.colors[color])
    sleep(.5)

display.display()
